version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GIT_BRANCH=local
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev"
